displayName: High Authentication Failures
combiner: OR
conditions:
- displayName: Auth Failures > 5 in 5m
  conditionThreshold:
    filter: metric.type="logging.googleapis.com/user/github_auth_failures"
    comparison: COMPARISON_GT
    threshold: 5
    duration: 300s
notificationChannels:
- projects/${PROJECT_ID}/notificationChannels/${CHANNEL_ID}