displayName: High API Latency
combiner: OR
conditions:
- displayName: API Latency > 2s
  conditionThreshold:
    filter: metric.type="logging.googleapis.com/user/github_api_latency"
    comparison: COMPARISON_GT
    threshold: 2
    duration: 300s
notificationChannels:
- projects/${PROJECT_ID}/notificationChannels/${CHANNEL_ID}