name: CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      
      - name: Validate GCP Authentication
        run: gcloud auth list
      
      - name: Run Deployment
        run: |
          cd automation
          chmod +x run.sh
          ./run.sh
      
      - name: Validate Deployment
        run: |
          cd automation
          chmod +x validate.sh
          ./validate.sh
      
      - name: Setup Monitoring
        run: |
          cd automation
          chmod +x monitor.sh
          ./monitor.sh
      
      - name: Notify Deployment Status
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./.github/workflows/notify.js')
            await script({github, context, core})
