name: CI Pipeline

on:
  push:
    branches: [ main, automation-fixes ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      
      - name: Run test suite
        run: |
          cd tests
          chmod +x run_tests.sh
          ./run_tests.sh

  lint:
    name: Shell Script Lint
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install shellcheck
        run: sudo apt-get install -y shellcheck
      
      - name: Run shellcheck
        run: |
          shellcheck automation/*.sh
          shellcheck tests/*.sh

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Run ShellCheck Security Scan
        run: |
          sudo apt-get install -y shellcheck
          shellcheck -S warning automation/*.sh
      
      - name: Run Trufflehog Secret Scan
        uses: trufflesecurity/trufflehog-actions-scan@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD